TeleStock/TeleStock/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TeleStock.Models
{
    public class Produit
    {
        [Key]
        public int produitID { get; set; }

        [Display(Name = "Code")]
        public string codeProduit { get; set; }


        [Display(Name = "Référence")]
        public string refProduit { get; set; }


        [Display(Name = "Désignation")]
        public string desProduit { get; set; }


        [Display(Name = "Prix Vte HT")]
        public decimal? prixVenteHtProduit { get; set; }


        [Display(Name = "Prix Achat HT")]
        public decimal? prixAchatHtProduit { get; set; }


        [Display(Name = "TVA")]
        public string tvaProduit { get; set; }

        [RegularExpression(@"^\d+.\d{0,2}$")]
        [Display(Name = "Qte En Stock")]
        public decimal? qteEnStockProduit { get; set; }


        [Display(Name = "Qte Rupture")]
        public decimal? qteRuptureProduit { get; set; }


        [Display(Name = "Qte Sur Stock")]
        public decimal? qteSurStockProduit { get; set; }


        [Display(Name = "Remarque")]
        public string remarqueProduit { get; set; }


        //public int EmployeeID { get; set; }
        //[Required(ErrorMessage = "This Field is Required")]
        //public string Name { get; set; }
        //[Required(ErrorMessage = "This Field is Required")]
        //public string Position { get; set; }
        //public string Office { get; set; }
        //public Nullable<int> Age { get; set; }
        //public Nullable<int> Salary { get; set; }


        //[Display(Name = "Release Date")]
        //[DataType(DataType.Date)]
        //public DateTime ReleaseDate { get; set; }
        //public string Genre { get; set; }

        //[Column(TypeName = "decimal(18, 2)")]
        //public decimal Price { get; set; }
    }
}

TeleStock/TeleStock/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeleStock.Models;

namespace TeleStock.Controllers
{
    public class ProduitsController : Controller
    {
        private readonly ProjectContext _context;

        public ProduitsController(ProjectContext context)
        {
            _context = context;
        }

        //
        // GET: /Employee/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            List<Produit> produitList = _context.Produits.ToList<Produit>();
            return Json(new { data = produitList });
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Produit());
            else
            {
                return View(_context.Produits.Where(x => x.produitID == id).FirstOrDefault<Produit>());
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Produit produit)
        {
            if (produit.produitID == 0)
            {
                _context.Produits.Add(produit);
                _context.SaveChanges();
                return Json(new { success = true, message = "Saved Successfully" });
            }
            else if (_context.Produits.Any(e => e.produitID == produit.produitID))
            {
                _context.Entry(produit).State = EntityState.Modified;
                _context.SaveChanges();
                return Json(new { success = true, message = "Updated Successfully" });
            }
            else
                return Json(new { success = false, message = "No Update" });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Produit emp = _context.Produits.Where(x => x.produitID == id).FirstOrDefault<Produit>();
            _context.Produits.Remove(emp);
            _context.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" });
        }




















        //private readonly ProjectContext _context;

        //public ProduitsController(ProjectContext context)
        //{
        //    _context = context;
        //}

        //// GET: Produits
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Produits.ToListAsync());
        //}

        //// GET: Produits/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var produit = await _context.Produits
        //        .SingleOrDefaultAsync(m => m.produitID == id);
        //    if (produit == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(produit);
        //}

        //// GET: Produits/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Produits/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("produitID,codeProduit,refProduit,desProduit,prixVenteHtProduit,prixAchatHtProduit,tvaProduit,qteEnStockProduit,qteRuptureProduit,qteSurStockProduit,remarqueProduit")] Produit produit)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(produit);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(produit);
        //}

        //// GET: Produits/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var produit = await _context.Produits.SingleOrDefaultAsync(m => m.produitID == id);
        //    if (produit == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(produit);
        //}

        //// POST: Produits/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("produitID,codeProduit,refProduit,desProduit,prixVenteHtProduit,prixAchatHtProduit,tvaProduit,qteEnStockProduit,qteRuptureProduit,qteSurStockProduit,remarqueProduit")] Produit produit)
        //{
        //    if (id != produit.produitID)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(produit);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ProduitExists(produit.produitID))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(produit);
        //}

        //// GET: Produits/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var produit = await _context.Produits
        //        .SingleOrDefaultAsync(m => m.produitID == id);
        //    if (produit == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(produit);
        //}

        //// POST: Produits/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var produit = await _context.Produits.SingleOrDefaultAsync(m => m.produitID == id);
        //    _context.Produits.Remove(produit);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ProduitExists(int id)
        //{
        //    return _context.Produits.Any(e => e.produitID == id);
        //}
    }
}

TeleStock/TeleStock/Views/Produits/AddOrEdit.cshtml
@model TeleStock.Models.Produit
@{
    Layout = null;
}


@using (Html.BeginForm("AddOrEdit", "Produits", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.produitID)

    <div class="form-group">
        <div class="row">
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.refProduit, new { @class = "control-label" })
                @Html.EditorFor(model => model.refProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.refProduit)
            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.desProduit, new { @class = "control-label" })
                @Html.EditorFor(model => model.desProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.desProduit)
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="form-group col-md-5">
                @Html.LabelFor(model => model.prixAchatHtProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.prixAchatHtProduit, new { htmlAttributes = new { @class = "form-control currency", autocomplete = "off" } })
                    <span class="input-group-addon">DA</span>
                </div>
            </div>
            <div class="form-group col-md-5">
                @Html.LabelFor(model => model.prixVenteHtProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.prixVenteHtProduit, new { htmlAttributes = new { @class = "form-control currency", autocomplete = "off" } })
                    <span class="input-group-addon">DA</span>
                </div>
            </div>
            <div class="form-group col-md-2">
                @Html.LabelFor(model => model.tvaProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.tvaProduit, new { htmlAttributes = new { @class = "form-control currency", autocomplete = "off" } })
                    <span class="input-group-addon">%</span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.qteEnStockProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.qteEnStockProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    <span class="input-group-addon">Qté</span>
                </div>
            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.qteRuptureProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.qteRuptureProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    <span class="input-group-addon">Qté</span>
                </div>
            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.qteSurStockProduit, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(model => model.qteSurStockProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    <span class="input-group-addon">Qté</span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.remarqueProduit, new { @class = "control-label" })
        @Html.EditorFor(model => model.remarqueProduit, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
        @Html.ValidationMessageFor(model => model.remarqueProduit)
    </div>

    <div class="form-group">
        <div class="row">
            <div class="form-group col-md-6">
                <button type="submit" class="btn btn-block btn-info"><i class="fa fa-floppy-o"></i> Submit</button>
            </div>
            <div class="form-group col-md-4">
                <button type="reset" class="btn btn-block btn-secondary"><i class="fa fa-repeat"></i> Reset</button>
            </div>
            <div class="form-group col-md-2">
                <button type="button" class="btn btn-block btn-warning" onclick="$('#pop').remove();"><i class="fa fa-window-close-o"></i> Close</button>
            </div>
        </div>
    </div>
}

<script>
       
    var regex = /^\d{0,9}(\.\d{0,2})?$/;
        $(".currency").on("keyup", function () {
            var valid = regex.test(this.value),
                val = this.value;
            var pos = this.selectionStart - 1;

            if (!valid) {
                if (typeof this.lastValid != "undefined") {
                    this.value = this.lastValid
                    this.setSelectionRange(pos, pos);
                } else {
                    this.value = "";
                }
            } else {
                this.lastValid = val;
            }
    });

    $(".currency").bind("paste", function (e) {
        // access the clipboard using the api
        var pastedData = e.originalEvent.clipboardData.getData('text');
        if (!regex.test(pastedData)) {
            e.preventDefault();
        }
    });
</script>

TeleStock/TeleStock/Views/Produits/Create.cshtml
@model TeleStock.Models.Produit

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="codeProduit" class="control-label"></label>
                <input asp-for="codeProduit" class="form-control" />
                <span asp-validation-for="codeProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="refProduit" class="control-label"></label>
                <input asp-for="refProduit" class="form-control" />
                <span asp-validation-for="refProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="desProduit" class="control-label"></label>
                <input asp-for="desProduit" class="form-control" />
                <span asp-validation-for="desProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prixVenteHtProduit" class="control-label"></label>
                <input asp-for="prixVenteHtProduit" class="form-control" />
                <span asp-validation-for="prixVenteHtProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prixAchatHtProduit" class="control-label"></label>
                <input asp-for="prixAchatHtProduit" class="form-control" />
                <span asp-validation-for="prixAchatHtProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tvaProduit" class="control-label"></label>
                <input asp-for="tvaProduit" class="form-control" />
                <span asp-validation-for="tvaProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qteEnStockProduit" class="control-label"></label>
                <input asp-for="qteEnStockProduit" class="form-control" />
                <span asp-validation-for="qteEnStockProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qteRuptureProduit" class="control-label"></label>
                <input asp-for="qteRuptureProduit" class="form-control" />
                <span asp-validation-for="qteRuptureProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qteSurStockProduit" class="control-label"></label>
                <input asp-for="qteSurStockProduit" class="form-control" />
                <span asp-validation-for="qteSurStockProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="remarqueProduit" class="control-label"></label>
                <input asp-for="remarqueProduit" class="form-control" />
                <span asp-validation-for="remarqueProduit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeleStock/TeleStock/Views/Produits/Delete.cshtml
@model TeleStock.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.codeProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.codeProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.refProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.refProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.desProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.desProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.prixVenteHtProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.prixVenteHtProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.prixAchatHtProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.prixAchatHtProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tvaProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tvaProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteEnStockProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteEnStockProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteRuptureProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteRuptureProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteSurStockProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteSurStockProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.remarqueProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.remarqueProduit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="produitID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TeleStock/TeleStock/Views/Produits/Details.cshtml
@model TeleStock.Models.Produit

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.codeProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.codeProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.refProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.refProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.desProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.desProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.prixVenteHtProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.prixVenteHtProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.prixAchatHtProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.prixAchatHtProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tvaProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tvaProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteEnStockProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteEnStockProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteRuptureProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteRuptureProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.qteSurStockProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.qteSurStockProduit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.remarqueProduit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.remarqueProduit)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.produitID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TeleStock/TeleStock/Views/Produits/Index.cshtml
@model IEnumerable<TeleStock.Models.Produit>
@{
    ViewBag.Title = "Produit List";
}

<h2>Produits</h2>

<a class="btn btn-info" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Produits")')"><i class="fa fa-plus"></i> Add New</a>
<table id="produitTable" class="table table-striped table-bordered display" style="width:100%">
    <thead>
        <tr>
            <th></th>
            <th>@Html.DisplayNameFor(model => model.refProduit)</th>
            <th>@Html.DisplayNameFor(model => model.desProduit)</th>
            <th>@Html.DisplayNameFor(model => model.prixVenteHtProduit)</th>
            <th>@Html.DisplayNameFor(model => model.prixAchatHtProduit)</th>
            <th>@Html.DisplayNameFor(model => model.tvaProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteEnStockProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteRuptureProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteSurStockProduit)</th>
            <th>@Html.DisplayNameFor(model => model.remarqueProduit)</th>
            <th></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th></th>
            <th>@Html.DisplayNameFor(model => model.refProduit)</th>
            <th>@Html.DisplayNameFor(model => model.desProduit)</th>
            <th>@Html.DisplayNameFor(model => model.prixVenteHtProduit)</th>
            <th>@Html.DisplayNameFor(model => model.prixAchatHtProduit)</th>
            <th>@Html.DisplayNameFor(model => model.tvaProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteEnStockProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteRuptureProduit)</th>
            <th>@Html.DisplayNameFor(model => model.qteSurStockProduit)</th>
            <th>@Html.DisplayNameFor(model => model.remarqueProduit)</th>
            <th hidden="hidden"></th>
        </tr>
    </tfoot>
</table>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" rel="stylesheet" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(document).keyup(function (e) {
            if (e.keyCode == 27) {
                $('#pop').remove();
            }
        });

        var Popup, dataTable;
        $(document).ready(function () {

            // Setup - add a text input to each footer cell
            $('#produitTable tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input type="text" required placeholder="Search ' + title + '" />');
            });

            // DataTable
            dataTable = $('#produitTable').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel', 'pdf', 'print'
                ],
                "ajax": {
                    "url": "/Produits/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "produitID" },
                    { "data": "refProduit" },
                    { "data": "desProduit" },
                    { "data": "prixVenteHtProduit" },
                    { "data": "prixAchatHtProduit" },
                    { "data": "tvaProduit" },
                    { "data": "qteEnStockProduit" },
                    { "data": "qteRuptureProduit" },
                    { "data": "qteSurStockProduit" },
                    { "data": "remarqueProduit" },
                    {
                        "data": "produitID", "render": function (data) {
                            return "<a class='btn btn-success btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Produits")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete(" + data + ")><i class='fa fa-trash'></i> Delete</a>";
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "150px"
                    }
                ],
                "language": {

                    "emptyTable": "No data found, Please click on <b>Add New</b> Button"
                },
                "aoColumnDefs": [{ "bVisible": false, "aTargets": [0] }]
            });

            // Apply the search
            dataTable.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that
                            .search(this.value)
                            .draw();
                    }
                });
            });

        });

        function PopupForm(url) {
            //alert(url);
            $('#pop').remove();
            var formDiv = $('<div id="pop"/>');
            $.get(url).done(function (response) {

                formDiv.html(response);
                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Fill Produit Details',
                    height: 510,
                    width: 800,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            $('#pop').remove();
            if (confirm('Are You Sure to Delete this Produit Record ?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Produits")/' + id,
                    success: function (data) {
                        if (data.success) {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "warn"
                            });
                        }
                    }
                });
            }
        }
    </script>
}

@*<script>
    $('.currency').keypress(function (e) {

        alert("currency3333");
    });
</script>*@